//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYHMember.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_BRZH
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ZHLB { get; set; }
        public string YHBH { get; set; }
        public string YHZH { get; set; }
        public string PASS { get; set; }
        public decimal GZZE { get; set; }
        public decimal ZHYE { get; set; }
        public decimal LJFY { get; set; }
        public decimal ZFDJE { get; set; }
        public decimal CEZFBL { get; set; }
        public decimal QTJE { get; set; }
        public decimal ZFPB { get; set; }
        public string BRKH { get; set; }
        public string brxm { get; set; }
    }
}
